# Generated by Django 6.0 on 2025-12-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expenselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fitness_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
