# Generated by Django 6.0 on 2025-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehicle_fitness_expiry_vehicle_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='internal_target_cost_per_km',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_year',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Four Wheeler', 'Four Wheeler'), ('Heavy Vehicle', 'Heavy Vehicle')], default='Four Wheeler', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], default='Petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='purpose',
            field=models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal'), ('Commute', 'Commute'), ('Delivery', 'Delivery')], default='Personal', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(choices=[('OWNED', 'Owned'), ('RENT', 'Temporary/Rented')], default='OWNED', max_length=20),
        ),
    ]
