# Generated by Django 6.0 on 2025-12-22 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_vehicle_internal_target_cost_per_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil', 'Oil Change'), ('tyre', 'Tyre Change'), ('general', 'General Service')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('odometer_reading', models.IntegerField(help_text='Odometer reading when service was done')),
                ('notes', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
            ],
        ),
    ]
