# Generated by Django 6.0 on 2025-12-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
