# Generated by Django 6.0 on 2025-12-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vehicle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='target_cost_per_km',
            field=models.FloatField(default=0.0, help_text='Target Cost per KM (e.g., 5.0)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='target_mileage',
            field=models.FloatField(default=0.0, help_text='Target km/L (e.g., 18.5)'),
        ),
    ]
