# Generated by Django 6.0 on 2026-01-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vehicle_target_cost_per_km_vehicle_target_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_year',
            field=models.IntegerField(default=2021),
        ),
    ]
