# Generated by Django 6.0 on 2026-01-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehicle_purchase_price_vehicle_purchase_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(default='1st Owner', max_length=50),
        ),
    ]
