# Generated by Django 6.0 on 2026-01-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('EV', 'EV'), ('Luxury', 'Luxury')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Ex-Showroom Price in Rupees', max_digits=12)),
                ('image_url', models.URLField(blank=True, help_text='Paste an image link from the internet', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
