# Generated by Django 6.0 on 2026-01-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_marketcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('car_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('EV', 'EV')], max_length=20)),
                ('price_lakhs', models.FloatField(help_text='Price in Lakhs (e.g. 7.5)')),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MarketCar',
        ),
    ]
