# Generated by Django 6.0 on 2026-01-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_newcar_delete_marketcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcar',
            name='image_url',
        ),
        migrations.AddField(
            model_name='newcar',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='new_launches/'),
        ),
        migrations.AlterField(
            model_name='newcar',
            name='price_lakhs',
            field=models.FloatField(),
        ),
    ]
