# Generated by Django 6.0 on 2026-01-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_newcar_image_url_newcar_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
